// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeubs5BEWyySIyHtVKUWUXizXKo5tbMhw',
    appId: '1:647362299120:web:1599bae22ccb2b3474ae35',
    messagingSenderId: '647362299120',
    projectId: 'rms-project-b8903',
    authDomain: 'rms-project-b8903.firebaseapp.com',
    storageBucket: 'rms-project-b8903.firebasestorage.app',
    measurementId: 'G-SK39VCZW83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-uZrHs3gPmkyFwFNDfm-Jov5H-2-5nY',
    appId: '1:647362299120:android:0c296ea5af3f551374ae35',
    messagingSenderId: '647362299120',
    projectId: 'rms-project-b8903',
    storageBucket: 'rms-project-b8903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADT06y7Wlxf6IBaAIxv7MaJpMBUaRV_64',
    appId: '1:647362299120:ios:abce1b8b9ad0bce374ae35',
    messagingSenderId: '647362299120',
    projectId: 'rms-project-b8903',
    storageBucket: 'rms-project-b8903.firebasestorage.app',
    iosBundleId: 'com.example.waiterPortal',
  );
}
