name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Waiter Portal
        uses: actions/checkout@v4
        with:
          path: waiter_portal

      - name: Checkout Shared Packages
        uses: actions/checkout@v4
        with:
          repository: https://github.com/SalihSarang/rms_packages.git 
          path: packages
    
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.8'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        working-directory: waiter_portal
        run: flutter pub get

      - name: Static Analysis
        working-directory: waiter_portal
        run: flutter analyze

      - name: Run Tests
        working-directory: waiter_portal
        run: flutter test
